- id: minio_storage
  version: 0
  name: Minio Storage
  description: Connect to a local Minio instance.
  variables:
    bucket:
      type: string
      help: The bucket to connect to.
    minio_access_key:
      type: string
      help: The access key for the Minio instance.
    minio_secret_key:
      type: string
      help: The secret key for the Minio instance.
  configuration:
    type: boto3
    auth:
#Up00tCrHvFkTz61pTQII
#Q7SZ9izcSSkioGeoQuiZ8eYa7peUNR6gdR4Rhfx7
      access_key: '{{ variables.minio_access_key }}'
      secret_key: '{{ variables.minio_secret_key }}'
    bucket:
      name: '{{ variables.bucket }}'
    connection:
      endpoint_url: 'http://minio:9000'
    badges:
    - type: slower
    - type: less_secure
    - type: less_stable
